### ISSUE TITLE
[FEATURE] aws-requests-auth layer or include package in elasticsearch layer

### ISSUE THREAD

**Issue by adriantomas** [keithrozario/Klayers#104]
**Describe the solution you'd like**
Would be great to count with `aws-requests-auth` or even better if it is included in the `elasticsearch` layer.

**Additional Packages**:
https://github.com/DavidMuller/aws-requests-auth

**Comment by keithrozario** [comment]
Let me take a look, you can try creating a pull request, by adding `aws-request-auth` to the  `Klayers/pipeline/config/Klayers-prodp38/packages.csv` file. That way when I merge it it'll be built on the next cycle.

**Comment by keithrozario** [comment]
I added this -- this will get built next Monday :) hope you enjoy it.

**Comment by adriantomas** [comment]
Thank you so much and sorry for my absence, I was on vacation!

**Comment by keithrozario** [comment]
Apologies, my mistake, this wasn't built because I only just merged the pull request. (the config is downloaded from this repo).

Latest layer can be found here:
https://api.klayers.cloud/api/v1/layers/latest/us-east-1/aws-requests-auth

replace `us-east-1` with your region of choice to obtain the arn
