### ISSUE TITLE
[BUG] Using pandas ARN is giving this error - [ERROR] ImportError: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.

### ISSUE THREAD

**Issue by ksachdeva11** [keithrozario/Klayers#124]
**Describe the bug**
I am using pandas ARN but seeing this error - 

`[ERROR] ImportError: Missing optional dependency 'fsspec'.  Use pip or conda to install fsspec.
`

I am using **pd.read_csv** in my code which gives me this error.

**Layer Version ARN:**

**arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-pandas:19**

**Framework:**
Serverless

Any inputs would be of great help. Thanks!

**Comment by ksachdeva11** [comment]
@keithrozario @adriaanbd - Any inputs would be of great help. Thanks!

**Comment by keithrozario** [comment]
Can you share your code. It sounds like you're trying to use another package on top of pandas.

**Comment by ksachdeva11** [comment]
```
import pandas as pd
import numpy as np

input = pd.read_csv(obj1['Body'], header=None)
```

It throws the above mentioned error at **read_csv** step. I am using `arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-pandas:19` ARN.

**Comment by keithrozario** [comment]
can you try adding this layer to your function, and see if it works. 

arn:aws:lambda:us-west-2:908645878701:layer:pylayers-python38-dev-fsspec:1

I typically expect the dependencies for pandas to be installed together (like numpy), but for some reason, fsspec isn't listed, and hence not installed. But it appears we need it :(

**Comment by mmlindeboom** [comment]
I am also getting this error using the latest pandas layer, I tried to add the above listed arn for fsspec and got the following error 

![Screen Shot 2020-11-02 at 7 35 25 PM](https://user-images.githubusercontent.com/1652063/97947604-a64c5700-1d42-11eb-8e18-ab78a732f000.png)

**Comment by mmlindeboom** [comment]
I have this error as well with the latest pandas layer release. Unfortunately I cannot use the above ARN for fsspec, I'm in us-east-1 region.

**Comment by ksachdeva11** [comment]
@keithrozario thanks for that. For some reason, it now works even without adding fsspec arn... not sure how. 

Had another question, just to confirm - ARN's which have expired/ deprecated will continue to work for lambda functions to which they were already added, right? Or do we need to keep updating the layers in our functions that have expired?

**Comment by keithrozario** [comment]
Hi @ksachdeva11,

You're correct. The ARNs that have expired will work as long as you don't re-deploy the lambda. (your function has a local copy it keeps).

Cloudformation/Terraform deployment will often leave the function as-is if no change has been made. Hence you might deploy a new application, but specific functions might be left in-tact.

The best way to ensure you have working copy all the time -- is to download a stable version of the package, and keep it in your deployed app, instead of relying on Klayers for this.

Klayers is built for folks seeking to prototype, experiment etc. Not for long-running applications. (although Klayers does itself use Klayers ... lol!!)

I'm thinking of creating LTS version of layers -- but just never got around to it.
