### ISSUE TITLE
No more spaCy?

### ISSUE THREAD

**Issue by jkhaui** [keithrozario/Klayers#63]
Hey,

These look great. I came here from your blog post looking for the spaCy layer, looks as if you removed it — any particular reason why?

**Comment by keithrozario** [comment]
Layer is still there actually, I just stopped publishing.

Spacy’s default installation size exceeds Lambdas limits. To make it fit, I manually removed all non-English language files. Since this project is fully automated, I removed from the list ....

I may re-introduce it, when I get around to automating builds for it — but for now, just take the arn from the blog post and use it ... you also use the get-layer-version command to download the layer as a zip, if you’re afraid I might delete it :)

**Comment by jkhaui** [comment]
Not worried about you deleting it, was just wondering if there was maybe an issue with the layer being the reason it was removed. But that answers my question, thanks!

**Comment by keithrozario** [comment]
Sure thing.
